apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: broker
        env:
        - name: JMX_PORT
          value: ""
